name: Deploy to server
on:
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR on Main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} << 'EOF'
            docker login -u "${{ vars.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            cd ${{ secrets.SERVER_PATH }}
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/it-tools-app:main
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/it-tools-api:main
            docker stop it-tools-app || true
            docker rm it-tools-app || true
            docker stop it-tools-api || true
            docker rm it-tools-api || true
            docker run -d --name it-tools-app --env-file .env -p 8009:80 ${{ vars.DOCKERHUB_USERNAME }}/it-tools-app:main
            docker run -d --name it-tools-api --env-file .env -p 3001:3001 ${{ vars.DOCKERHUB_USERNAME }}/it-tools-api:main
          EOF